# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: go run mycustomaction.go
      shell: bash